### PR TITLE
[WIP] add missing name service switch libraries

### PR DESCRIPTION
**Pull request by n3ph**
Adding name service switch library.

### CODE REVIEW

**Comment by n3ph** [comment]
Why are we using `--with-bdeps=y`? Man page states this is enabled by default.

Also, how am I supposed to test this locally?

**Comment by WhatAmISupposedToPutHere** [comment]
> Adding name service switch library.

What is it for?

> Why are we using --with-bdeps=y

cargo-culting and supersition

> Also, how am I supposed to test this locally?

If you are only changing the catalyst files, get an x86 box and run catalyst on that, if you are changing other stuff - you don't, fork the repo and do all the tests in github ci, yes it sucks and takes forever, but there is effectively no other options.


As for change, please add it at the end, on a separate line, the only reason fuse and gtk are specified like this, is that they are slotted and colons confuse catalyst's config parser.

**Comment by WhatAmISupposedToPutHere** [comment]
Edit: i was wrong,  with-bdeps is actually needed, otherwise emerge it will not install them if installing from cache.

**Comment by n3ph** [comment]
> What is it for?

Dependency of Machinarium (Game)
  
> As for change, please add it at the end, on a separate line, the only reason fuse and gtk are specified like this, is that they are slotted and colons confuse catalyst's config parser.

👍🏼

**Comment by n3ph** [comment]
Done with 89459dc4615a47314c961bcba81c5aa8cac3eff9

**Pull request closed without merging**
